/*
 * This Groovy source file was auto generated by running 'gradle buildInit --type groovy-library'
 * by 'Masaya' at '16/06/12 16:19' with Gradle 2.1
 *
 * @author Masaya, @date 16/06/12 16:19
 */
class Library {
    boolean someLibraryMethod() {
        true
    }
}
