/*
 * This Spock specification was auto generated by running 'gradle init --type groovy-library'
 * by 'Masaya' at '16/06/12 16:19' with Gradle 2.1
 *
 * @author Masaya, @date 16/06/12 16:19
 */

import spock.lang.Specification

class LibraryTest extends Specification{
    def "someLibraryMethod returns true"() {
        setup:
        Library lib = new Library()
        when:
        def result = lib.someLibraryMethod()
        then:
        result == true
    }
}
